### ISSUE TITLE
Auto builds miss libva-drm.so

### ISSUE THREAD

**Issue by alculete** [ubuntu-flutter-community/musicpod#186]
**ProblemType**
Bug

**Date**
Thu Sep 14 23:09:45 2023

**CurrentDesktop**
ubuntu:GNOME

**ProcEnviron**
LANG=en_US.UTF-8
PATH=(custom, no user)
SHELL=/bin/bash
TERM=xterm-256color
XDG_RUNTIME_DIR=<set>

**DistroRelease**
Ubuntu 23.04

**Uname**
Linux 6.2.0-32-generic x86_64

**Architecture**
amd64

**Snap**
musicpod 0+git.291662c (latest/stable)

**SnapChanges**
ID   Status  Spawn                      Ready                      Summary
11   Done    2023-09-14T23:05:07+02:00  2023-09-14T23:06:08+02:00  Install "musicpod" snap
13   Done    2023-09-14T23:07:52+02:00  2023-09-14T23:08:45+02:00  Refresh "musicpod" snap from "latest/edge" channel
14   Done    2023-09-14T23:09:17+02:00  2023-09-14T23:09:21+02:00  Refresh "musicpod" snap from "latest/stable" channel

**SnapConnections**
Interface                Plug                              Slot                            Notes
audio-playback           musicpod:audio-playback           :audio-playback                 -
content[gnome-42-2204]   musicpod:gnome-42-2204            gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]    musicpod:gtk-3-themes             gtk-common-themes:gtk-3-themes  -
content[icon-themes]     musicpod:icon-themes              gtk-common-themes:icon-themes   -
content[sound-themes]    musicpod:sound-themes             gtk-common-themes:sound-themes  -
dbus                     -                                 musicpod:dbus-musicpod          -
desktop                  musicpod:desktop                  :desktop                        -
desktop-legacy           musicpod:desktop-legacy           :desktop-legacy                 -
gsettings                musicpod:gsettings                :gsettings                      -
home                     musicpod:home                     :home                           -
mpris                    -                                 musicpod:mpris                  -
network                  musicpod:network                  :network                        -
network-manager-observe  musicpod:network-manager-observe  :network-manager-observe        -
opengl                   musicpod:opengl                   :opengl                         -
removable-media          musicpod:removable-media          -                               -
wayland                  musicpod:wayland                  :wayland                        -
x11                      musicpod:x11                      :x11                            -

**SnapInfo.musicpod**
name:      musicpod
summary:   Music, podcast and internet radio player for your Ubuntu Desktop
publisher: Frederik Feichtmeier
store-url: https://snapcraft.io/musicpod
contact:   https://github.com/ubuntu-flutter-community/musicpod
license:   MPL-2.0
description: |
  Play local audio files, browse podcasts online or listen to internet radio
  stations - all in one app!
  
  - Play local audio files (mp3, flac, m4a, mp4)
  - Find your local audio library sorted by metadata
  - Search for local audio files sorted by title, album and artist
  - Play internet radio stations and search them by tag, name or country
  - Play podcasts and find them by country, topic and name
  - Pin your favorite albums, podcasts and stations to the sidebar
  - Collect your favorite songs with the heart button
  
  The podcast and radio features do currently need internet access and thus
  the network-manager-observe permission is being used to display a
  disconnect from the internet in the user interface.
  
  MusicPod should automatically connect to the network-manager-observe
  interface. If it didn't you can connect it with the following command:
  
  `sudo snap connect musicpod:network-manager-observe`
commands:
  - musicpod
snap-id:      sxdOSGRbzsWhPmGrkYYAs68rzieTrIiv
tracking:     latest/stable
refresh-date: 2023-09-14T23:09:17+02:00
channels:
  latest/stable:    0+git.291662c 2023-09-11T14:16:24Z (479) 53MB -
  latest/candidate: ^                                             
  latest/beta:      ^                                             
  latest/edge:      0+git.75f1d84 2023-09-05T10:53:42Z (477) 53MB -
installed:          0+git.291662c                      (479) 53MB -

**SnapInfo.core22**
name:      core22
summary:   Runtime environment based on Ubuntu 22.04
publisher: Canonical**
store-url: https://snapcraft.io/core22
license:   unset
description: |
  The base snap based on the Ubuntu 22.04 release.
type:         base
snap-id:      amcUKQILKXHHTlmSa7NMdnXSx02dNeeT
tracking:     latest/stable
refresh-date: 2023-04-18T22:37:22+02:00
channels:
  latest/stable:    20230801 2023-08-30T22:10:06Z (864) 77MB -
  latest/candidate: 20230801 2023-08-03T14:05:28Z (864) 77MB -
  latest/beta:      20230801 2023-08-02T00:05:49Z (864) 77MB -
  latest/edge:      20230914 2023-09-14T20:26:43Z (910) 77MB -
installed:          20230325                      (607) 76MB base

**SnapInfo.gtk-common-themes**
name:      gtk-common-themes
summary:   All the (common) themes
publisher: Canonical**
store-url: https://snapcraft.io/gtk-common-themes
license:   unset
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.
snap-id:      jZLfBRzf1cYlYysIjD2bwSzNtngY0qit
tracking:     latest/stable/ubuntu-23.04
refresh-date: 2023-04-18T22:37:25+02:00
channels:
  latest/stable:    0.1-81-g442e511 2022-06-28T18:10:06Z (1535) 96MB -
  latest/candidate: 0.1-81-g442e511 2022-06-24T16:30:46Z (1535) 96MB -
  latest/beta:      0.1-81-g442e511 2022-06-24T16:30:46Z (1535) 96MB -
  latest/edge:      ^                                                
installed:          0.1-81-g442e511                      (1535) 96MB -

**SnapInfo.gnome-42-2204**
name:      gnome-42-2204
summary:   Shared GNOME 42 Ubuntu stack
publisher: Canonical**
store-url: https://snapcraft.io/gnome-42-2204
license:   unset
description: |
  This snap provides the GNOME 42 stack to other snaps that use it. It shares
  the base GNOME libraries and desktop integration components through the
  content interface. This helps reduce the size of snaps and helps developers
  to easily snap desktop applications.
  
  **For users**
  
  This snap is automatically installed and removed when needed. **Manually
  adding or removing this snap is not recommended** and might break things.
  
  * If you are having issues with **snaps** using GNOME, please contact the
  experts on the Snapcraft forum: https://forum.snapcraft.io/
  * If you want to install the GNOME Desktop Environment, then you are in the
  wrong place. Please take a look at https://www.gnome.org/ for more
  information on how to get it.
  
  **For developers**
  
  * The `gnome` extension is the recommended way to use this in your own
  snap: https://snapcraft.io/docs/gnome-extension
  * You can report issues with this content snap on GitHub:
  https://github.com/ubuntu/gnome-sdk/issues
  * The source code of this snap is available on GitHub in the
  `gnome-42-2204` branch:
  https://github.com/ubuntu/gnome-sdk/tree/gnome-42-2204
snap-id:      lATO8HzwVvrAPrlZRAWpfyrJKlAJrZS3
tracking:     latest/stable/ubuntu-23.04
refresh-date: 2023-04-18T22:37:23+02:00
channels:
  latest/stable:    0+git.ff35a85 2023-08-09T05:10:04Z (126) 509MB -
  latest/candidate: 0+git.ff35a85 2023-09-14T15:29:23Z (132) 521MB -
  latest/beta:      ^                                              
  latest/edge:      0+git.ff35a85 2023-09-14T15:29:23Z (132) 521MB -
installed:          0+git.e7d97c7                       (87) 482MB -

**SnapGitOwner**
ubuntu-flutter-community

**SnapGitName**
musicpod

**CrashDB**
snap-github

**NonfreeKernelModules**
nvidia_modeset nvidia

**InstallationMedia**
Ubuntu 23.04 "Lunar Lobster" - Release amd64 (20230418)

**Tags**
 lunar

**InstallationDate**
Installed on 2023-09-14 (0 days ago)

**UpgradeStatus**
No upgrade log present (probably fresh install)

**ProcVersionSignature**
Ubuntu 6.2.0-32.32-generic 6.2.16

**ProcCpuinfoMinimal**
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 140
model name	: 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
stepping	: 2
microcode	: 0x2c
cpu MHz		: 4296.478
cache size	: 12288 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 27
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear ibt flush_l1d arch_capabilities
vmx flags	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple pml ept_mode_based_exec tsc_scaling
bugs		: spectre_v1 spectre_v2 spec_store_bypass swapgs eibrs_pbrsb gds
bogomips	: 5836.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

**ApportVersion**
2.26.1-0ubuntu2

**CasperMD5CheckResult**
pass

**Comment by alculete** [comment]
The error was 
`/snap/musicpod/479/bin/musicpod: error while loading shared libraries: libva-drm.so.2: cannot open shared object file: No such file or directory`

**Comment by Feichtmeier** [comment]
:thinking: thats weird, the snap should install all .so files etc inside
@kenvandine do you have any good idea why this might be missing externally?

**Comment by Feichtmeier** [comment]
@alculete just pushed a manually built snap of musicpod to the store could you refresh and check if the error is gone?
theory: this only happens to auto built snaps from snapcraft 🤔

**Comment by alculete** [comment]
This version is working

**Comment by Feichtmeier** [comment]
Awesome 😃 
Okay then it's really the automated build

**Comment by alculete** [comment]
I'm closing this issue, since is solved.

**Comment by Feichtmeier** [comment]
Hm hm eventually not. At least not for auto builds

**Comment by kenvandine** [comment]
Can anyone confirm that it's still an issue for the auto build?  That file is actually provided by the gnome-42-2204 content snap.  I suspect the case where it didn't work was the namespace was out of whack and a reboot would have resolved it.  We've seen that happening when refreshing between channels like that and using content snaps.  We recently fixed a bug in that area of snapd, but that might not have made it to stable yet.

**Comment by Feichtmeier** [comment]
I think this is no longer an issue
sorry for the late reply
